README.md, lib/ably/models/paginated_resource.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/presence.rb, lib/ably/rest/channel.rb, lib/ably/rest/presence.rb, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_history_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/acceptance/rest/channel_spec.rb, spec/acceptance/rest/message_spec.rb, spec/acceptance/rest/presence_spec.rb, spec/acceptance/rest/stats_spec.rb, spec/unit/models/paginated_resource_spec.rb
This PR provides an API that matches the proposal at https://github.com/ably/ably-js/issues/28
=> New paginated resource

lib/ably/exceptions.rb, lib/ably/models/channel_state_change.rb, lib/ably/models/connection_state_change.rb, lib/ably/models/message.rb, lib/ably/models/presence_message.rb, lib/ably/models/protocol_message.rb, lib/ably/modules/state_emitter.rb, lib/ably/modules/uses_state_machine.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/channel/channel_state_machine.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/realtime/connection/connection_state_machine.rb, lib/ably/rest/channel.rb, lib/ably/util/crypto.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/acceptance/rest/channel_spec.rb, spec/unit/models/channel_state_change_spec.rb, spec/unit/models/connection_state_change_spec.rb, spec/unit/util/crypto_spec.rb
This PR fixes a number of issues:
* https://github.com/ably/ably-ruby/issues/56
* https://github.com/ably/ably-ruby/issues/53
* https://github.com/ably/ably-ruby/issues/52 (note I have added ConnectionStateChange and ChannelStateChange objects, ChannelStateChange is not part of the spec but will likely be in 0.9)
* https://github.com/ably/ably-ruby/issues/50
FYI @paddybyers and @SimonWoolf
=> Spec update to fix a number of issues

lib/ably/models/protocol_message.rb, lib/ably/models/token_details.rb, lib/ably/models/token_request.rb, lib/ably/modules/async_wrapper.rb, lib/ably/realtime/presence.rb, spec/acceptance/realtime/presence_history_spec.rb, spec/acceptance/realtime/presence_spec.rb
=> Various fixes for open issues

spec/acceptance/realtime/message_spec.rb
@paddybyers @tcard FYI, this is my implementation of interoperability with Ruby.
Note that:
* These tests explicitly don't use MsgPack as the encodings are different. I am not sure if we want separate tests for MsgPack, I would assume we do, but much harder to do as a raw test I would imagine.
* This depends on some updates I made in https://github.com/ably/ably-common/pull/18, specifically the `expectedHexValue` attribute.
See https://github.com/ably/ably-ios/pull/459 and https://github.com/ably/ably-common/pull/16
=> Ensure interoperability with other libraries with JSON protocol

lib/ably.rb, lib/ably/exceptions.rb, lib/ably/realtime/client.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/rest/client.rb, lib/ably/version.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/rest/client_spec.rb
@SimonWoolf for when you're back from holiday, a few fixes including some for the fallback host functionality, see https://github.com/ably/ably-ruby/issues/95
=> Fallback host improvements

spec/acceptance/rest/channel_spec.rb
Per Slack discussion https://ably-real-time.slack.com/archives/C030APSH3/p1524044265000492
=> Improve pagination history test

ably.gemspec
See https://github.com/eventmachine/eventmachine/issues/756
We experienced this problem in CI quite often
=> Fix race condition in EventMachine

lib/ably/rest/client.rb
=> Add request_id attribute documentation

lib/ably/auth.rb, lib/ably/rest/client.rb, spec/acceptance/rest/auth_spec.rb, spec/acceptance/rest/client_spec.rb, spec/unit/rest/client_spec.rb
Adds fallback cacheing, see https://github.com/ably/docs/pull/554
Was a little more tricky than I thought in fact... I was expecting a 10 minute job, was at least 2 hours of work :(
=> Rsc15f remember fallback

.editorconfig
See http://editorconfig.org/ and https://github.com/ably/docs/issues/427
=> Add .editorconfig for basic IDE configuration settings

.travis.yml, lib/ably/realtime/client.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/unit/realtime/connection_spec.rb
Fixes:
* https://github.com/ably/ably-ruby/issues/179
* https://github.com/ably/ably-ruby/issues/180
=> msgSerial fixes including connection recovery fix

lib/ably/exceptions.rb, spec/support/test_app.rb
Per [the plan](https://docs.google.com/document/d/1fhbQWQaoIe-urizplgNtT4WxPRgoUDchg-VIBnAEqA0/edit?usp=sharing) (internal link).
=> Rename master to main

lib/ably/rest/channel.rb, lib/ably/rest/client.rb, spec/acceptance/rest/channel_spec.rb
Fixes https://github.com/ably/ably-ruby/issues/209
=> RestChannel#publish: implement params (RSL1l)

.travis.yml, lib/ably/rest/client.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/push_admin_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/acceptance/rest/client_spec.rb, spec/acceptance/rest/push_admin_spec.rb, spec/spec_helper.rb, spec/support/serialization_helper.rb
Resolves https://github.com/ably/ably-ruby/issues/168.
It also refactors serialization/deserialization of objects in stubs
It's based on https://github.com/ably/ably-ruby/pull/214 to reduce specs time
=> Add support for delete, patch, put method in #request

README.md, lib/ably/realtime/client.rb, lib/ably/realtime/connection.rb, spec/acceptance/realtime/connection_spec.rb, spec/unit/realtime/client_spec.rb
Resolve https://github.com/ably/ably-ruby/issues/176
=> Add transport_params option to realtime client (RTC1f1)

spec/acceptance/realtime/presence_spec.rb
Resolves https://github.com/ably/ably-ruby/issues/163
=> Validate that members presenceMap does not change on synthesized leave

CHANGELOG.md, README.md
=> Document libcurl requirement

lib/ably/rest/channel.rb
=> Fix documentation for Channel#publish

ably.gemspec
=> Upgrade rspec to 3.10

lib/ably/models/protocol_message.rb, spec/unit/models/protocol_message_spec.rb
TR3f
Resolves #274 
Added `ProtocolMessage#has_attach_resume_flag?`
=> Add support for DataTypes ProtocolMessage: has_attach_resume_flag?

CHANGELOG.md
Focus on customer-facing changes.
=> Improve 1.2.0 changelog

.github/workflows/.rspec_parallel, .github/workflows/check.yml, spec/acceptance/realtime/message_spec.rb
=> Fix test-observability uploads issues

spec/acceptance/realtime/connection_spec.rb
See [internal slack thread](https://ably-real-time.slack.com/archives/C02P7F81DPS/p1664792520213559)
=> test: remove deprecated recover behaviour spec

spec/acceptance/realtime/channel_history_spec.rb
=> [ECO-4847] Fix until attach serial test

.github/workflows/check.yml
this will allow us to manually run tests against sandbox using the github.com UI
=> ci: enable workflow_dispatch
