lib/ably/realtime/connection/connection_manager.rb, spec/acceptance/realtime/connection_failures_spec.rb
As per documentation the retry frequency for disconnected need to be
every 15 seconds for 2 minutes and the retry frequency for suspended
needs to be every 2 minutes for as long as necessary.
First time I actually have a valid use case for `Float::INFINITY` :)
=> Fix connection retry frequency

SPEC.md, lib/ably/auth.rb, lib/ably/exceptions.rb, lib/ably/modules/message_emitter.rb, lib/ably/realtime.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/channel/channel_state_machine.rb, lib/ably/realtime/client.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/client/outgoing_message_dispatcher.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/realtime/connection/connection_state_machine.rb, lib/ably/realtime/connection/websocket_transport.rb, lib/ably/realtime/presence.rb, lib/ably/realtime/presence/members_map.rb, lib/ably/realtime/presence/presence_manager.rb, lib/ably/realtime/presence/presence_state_machine.rb, lib/ably/rest/presence.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/unit/realtime/channel_spec.rb, spec/unit/realtime/channels_spec.rb, spec/unit/realtime/connection_spec.rb, spec/unit/realtime/presence_spec.rb
@kouno and @paddybyers, I have implemented the Presence Members Map in this pull request so that it matches the agreed functionality, namely that presence does not wait for a SYNC to complete, but will instead be initiated by the server on channel attach, but will emit any events that are received whilst performing the sync.  I therefore keep a map of members that have had more recent updates and ignore older updates.
Few things to bear in mind:
* I have been unable to test SYNC recovery, see https://github.com/ably/realtime/issues/91 and https://github.com/ably/ably-ruby/compare/presence-map?expand=1#diff-c9dcfc1419f386559fc4a8a0ef368c99R1323
* I have also implemented correct failure callbacks now for all `Deferrables` in Channels and Presence i.e. if you call `#enter` and the channel is …
=> Presence Member Map

lib/ably/models/stat.rb, lib/ably/models/stat_types.rb, spec/acceptance/rest/stats_spec.rb, spec/unit/models/stat_spec.rb
Followed convention use in Java library for stats whereby a Hash is not returned by instead a typed object is returned.
Where sparse stats (i.e. no key / value pair when zero) are returned from the API, a value of zero is returned
@paddybyers and @kouno as discussed today, this is now implemented in our Admin API and now in the Ably Ruby library.  I have tested this against the sparse stats realtime branch.
Please shout if you have any feedback.
=> Typed stats similar to Java library + zero default for empty stats

.gitignore, README.md, ably.gemspec, spec/spec_helper.rb
@rjeczalik I have added coveralls support.  Once the build is done we should have coverage reporting.  Currently on the home page it says unknown coverage, see https://github.com/ably/ably-ruby/tree/coveralls.io
@kouno and @paddybyers seems sensible to add coveralls.io to all of our client libraries.  WDYT?
=> Add coveralls.io coverage reporting

SPEC.md, spec/acceptance/rest/presence_spec.rb, spec/support/test_app.rb
@kouno following our discussion, I added new encoded & encrypted fixture presence data that is sent to Ably when setting up the Test App.  I believe we only really need one Presence specific test for decoding of data via REST as Messages already have extensive test coverage and this simply ensures that we have an acceptance test communicating with the Ably service without any stubbing.
This includes:
* Set up encoded & encrypted presence data when setting up a test app
* Added tests for presence#get and presence#history that ensure that presence messages retrieved are decoded as expected.
* Updated the API Spec
Would you like to show this to Matus?
=> Test encoded presence fixture data for #get & #history

SPEC.md, lib/ably/modules/async_wrapper.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/presence.rb, lib/ably/rest/channel.rb, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/presence_history_spec.rb, spec/unit/models/paginated_resource_spec.rb, spec/unit/modules/async_wrapper_spec.rb
@kouno and @paddybyers following our chat, here is my proposal to support history requests on real-time channels that only give you messages published before the channel attached.
Please tell me what you think as we should probably add this or something like this to the other real-time client libraries.
=> History since attach

lib/ably/exceptions.rb, lib/ably/modules/conversions.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/presence.rb, lib/ably/rest/channel.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/acceptance/rest/message_spec.rb, spec/acceptance/rest/presence_spec.rb
@SimonWoolf & @paddybyers following our discussion today, commit c3309fd ensures that non supported data payload types raise an exception immediately.
I had to add a new error code too, see https://github.com/ably/ably-common/commit/5ea9a3334309f9e108f1bed2ffff09c70043a043
Can you tell me if you are happy with this?  If so, I will amend our [feature documentation](http://docs.ably.io/client-lib-development-guide/features/) and communicate this out to everyone.
FYI @kouno
=> Reject invalid payload type

lib/ably.rb
The order files are returned by Dir.glob is [unspecified and OS-dependent](http://ruby-doc.org/core-2.2.2/Dir.html#method-c-glob), which was causing odd behaviour on Linux. Add a sort to ensure files are required in a consistent order across all OSes
=> Ensure files are required in a consistent order

README.md, lib/ably/auth.rb, lib/ably/realtime/auth.rb, lib/ably/realtime/connection.rb, lib/ably/rest/client.rb, spec/acceptance/realtime/auth_spec.rb, spec/acceptance/realtime/channels_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/acceptance/rest/channel_spec.rb, spec/acceptance/rest/client_spec.rb, spec/shared/client_initializer_behaviour.rb, spec/unit/auth_spec.rb
@paddybyers following our chat a little while ago about how I had merged auth options and token params into a single argument, I have now split them, addressing https://github.com/ably/ably-ruby/issues/55
I am doing this so that the Realtime spec is valid for Ruby...
Not expecting a reply, just wanted you to see
=> Separate token params for auth

lib/ably/auth.rb, spec/acceptance/rest/client_spec.rb
Thought I'd add a test to check ably-ruby didn't have the problem of https://github.com/ably/ably-js/issues/108 , needed a tweak to make it pass
=> Allow clientId to be provided on init if using externally created token

lib/ably/auth.rb, lib/ably/models/token_details.rb, lib/ably/modules/conversions.rb, lib/ably/modules/state_emitter.rb, lib/ably/modules/uses_state_machine.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/channel/channel_state_machine.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/client/outgoing_message_dispatcher.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/realtime/connection/connection_state_machine.rb, lib/ably/realtime/presence.rb, spec/acceptance/realtime/auth_spec.rb, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/channels_spec.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_history_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/acceptance/realtime/stats_spec.rb, spec/acceptance/realtime/time_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/support/event_machine_helper.rb, spec/unit/models/token_details_spec.rb, spec/unit/modules/async_wrapper_spec.rb
@paddybyers FYI, I now close all connections automatically, which unfortunately unearthed a LOT of small issues in the Ruby lib to do with the library shutting down which weirdly, before this, had very little coverage.
So far, it appears that the account limits issue is no longer a problem, see https://travis-ci.org/ably/ably-ruby.  Some tests are failing, but those are primarily known problems in realtime.  This addresses https://github.com/ably/realtime/issues/296
=> Ensure connections are always closed in tests

.travis.yml, ably.gemspec, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/spec_helper.rb, spec/support/debug_failure_helper.rb
I have been seeing intermittent failures in the Ruby test suite in Travis, so I have now added a wrapper for the tests that collects verbose logs and only outputs the detail if the test fails.  This is going to be hugely useful in debugging issues we see in CI, at least for Ruby ayway.
FYI @SimonWoolf @paddybyers
=> Output detailed log for any text failures

.travis.yml, ably.gemspec, lib/ably/auth.rb, lib/ably/modules/state_emitter.rb, lib/ably/realtime/auth.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/connection.rb, spec/acceptance/realtime/auth_spec.rb, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/acceptance/realtime/time_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/spec_helper.rb, spec/support/debug_failure_helper.rb
@paddybyers I have enabled all the tests in `ably-ruby` that were blocked by issues in realtime now, and so far things look good.  I still have some intermittent failures, but I will try to get to the bottom of them and provide more detail once I see some patterns.
Some notes:
* I ask for next page and expect 0-x items, see c996a5ce44e589325e73658fa255f7878d3bca56, seems to be working
* I implemented the `clientIdValidated` attribute on the `Auth` object because it was 80% implemented anyway, see https://github.com/ably/docs/pull/71 and 690caac
* Issue https://github.com/ably/realtime/issues/256 is no longer an issue
* Token issue https://github.com/ably/realtime/issues/343 is no longer an issue
* I can confirm that publishing over REST with a connection key now works as expected (publish …
=> Some intermittent test fixes & enable tests that were blocked

lib/ably/modules/message_emitter.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/presence_spec.rb
Fixes immediate issue in https://github.com/ably/docs/issues/108
=> Ensure message emitter callbacks are safe (i.e. cannot break the EM)

lib/ably/auth.rb, lib/ably/realtime/auth.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/rest/client.rb, spec/acceptance/realtime/auth_spec.rb, spec/acceptance/rest/auth_spec.rb
This mirrors the work at https://github.com/ably/ably-js/pull/261, however it tests a few more edge cases. The tests to upgrade capabilities or client_id are marked as pending (`skip`).
See https://github.com/ably/docs/pull/113 for the related spec
@paddybyers @SimonWoolf @lmars
=> Reauthorise

lib/ably/models/message.rb, lib/ably/models/message_encoders/base.rb, lib/ably/models/message_encoders/base64.rb, lib/ably/models/presence_message.rb, lib/ably/modules/encodeable.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/presence.rb, lib/ably/realtime/presence/members_map.rb, lib/ably/rest/channel.rb, lib/ably/rest/client.rb, lib/ably/rest/presence.rb, spec/unit/models/message_spec.rb, spec/unit/models/presence_message_spec.rb
FYI @paddybyers @SimonWoolf 
I have implemented `fromEncoded` and `fromEncodedArray` defined in https://github.com/ably/docs/pull/182/files.
It was a bit harder than JS specifically because the encoders are registered with the client, yet the static Message object is not associated with a client.
Shout if you're happy and I'll merge into 0.9
=> From encoded

lib/ably/realtime/connection.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb
This PR fixes two critical issues:
* [Host header was not being set correctly](https://github.com/ably/ably-ruby/issues/117) in fallback hosts over realtime
* Fallback hosts were being used in all conditions where a transport failed as opposed to only when a connect attempt failed and thus the request was a subsequent attempt to connect to Ably. This issue only existed for realtime connections.
=> Fallback fixes

lib/ably/rest/channel.rb, lib/ably/rest/presence.rb, spec/acceptance/rest/channel_spec.rb, spec/acceptance/rest/presence_spec.rb
This PR is just [@smeyfroi's PR](https://github.com/ably/ably-ruby/pull/118) plus one additional test to prevent a regression.
=> Channel name encoding error for REST requests

.travis.yml
=> Add Ruby 2.1 and 2.3 to Travis tests

spec/acceptance/rest/auth_spec.rb
There's a new `40104` code for invalid timestamp. 
This fixes the related ruby test.
=> Fix failing auth test

spec/acceptance/realtime/presence_history_spec.rb
Couldn't come up with a better idea at the moment :(
=> Fix presence history test

spec/acceptance/realtime/channel_history_spec.rb
This fixes another "last? is true but there's a next page with 0 items" pagination test.
=> Fix channel history pagination test

lib/ably/auth.rb, lib/ably/models/message.rb, lib/ably/models/presence_message.rb, lib/ably/modules/conversions.rb, lib/ably/realtime/channel.rb, lib/ably/rest/channel.rb, spec/unit/rest/channel_spec.rb
Pretty straight forward fix.  As Ruby moves towards making all string literals frozen by default, more people might hit problems with this as time goes on.
Fixes https://github.com/ably/ably-ruby/issues/132
=> Do not encode strings in-place

ably.gemspec, lib/ably/realtime/connection.rb, spec/acceptance/realtime/connection_spec.rb
Fixes https://github.com/ably/ably-ruby/issues/116
We can now use native heartbeats with the Ably lib thanks to @jcoglan merging in [my ping/pong PR](https://github.com/faye/websocket-driver-ruby/pull/51)
=> Add support for WebSocket native heartbeats

lib/ably/auth.rb, lib/ably/modules/encodeable.rb, lib/ably/rest/client.rb, spec/acceptance/realtime/auth_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/acceptance/rest/client_spec.rb, spec/shared/client_initializer_behaviour.rb, spec/spec_helper.rb, spec/support/test_logger_helper.rb, spec/unit/logger_spec.rb
Unfortunately @funkyboy's implementation did not have test coverage with the new request ID for publish operations, and such, his work introduced a regression.
This PR fixes that, but also:
* Improves those tests marginally
* Fixes a few incorrect calls to potentially private method
* Adds a shared logger for inspecting log output
* [Always logs the outcomes of retry requests](https://github.com/ably/docs/issues/359). I believe this will significantly help people when debugging requests that are retried as the logs will make more sense.
=> Add request id fix for bulk publishes

lib/ably/auth.rb
doing a quick auth_method test in ably-ruby, ran across this
=> Fix auth_method->auth_params

lib/ably/rest/channel.rb, lib/ably/rest/client.rb, lib/ably/version.rb, spec/acceptance/rest/message_spec.rb, spec/unit/models/message_spec.rb
Unless I am mistaken, we don't have a spec for idempotent publishing, so I have created this PR to help us define what functionality we may to include in the spec for this. See issue at https://github.com/ably/docs/issues/469 relating to idempotent publishing in the spec.
Note:
* I additionally added a new ClientOptions as a beta feature that enables idempotent publishing to all publishes.  It's disabled by default. I propose this is included in 1.1.
* When we release 1.2, we may want to consider enabling this feature by default.
=> Idempotent publishing

lib/ably/models/protocol_message.rb, lib/ably/realtime/channel.rb, lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/channel/channel_state_machine.rb, lib/ably/realtime/channel/publisher.rb, lib/ably/realtime/client.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/connection.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/client_spec.rb
This PR adds support for transient publishing as defined in the spec atL:
* https://github.com/ably/docs/pull/323/files
* https://github.com/ably/docs/pull/470
I thought it would be useful to additionally see what's involved in support transient publishing from the proposed `Client#publish` method defined at https://github.com/ably/docs/issues/468.  Interested to hear your views on this.
=> Transient publishing for #164

README.md
Please note that the spec item currently links to the staging site as on the main website, the individual spec items can't be linked. I have raised an issue, however: https://github.com/ably/website/issues/2126
=> Known limitations section in README

ably.gemspec, lib/ably/rest/client.rb
Fixes https://github.com/ably/ably-ruby-rest/issues/11 by allowing more modern version of Faraday to be used
Fixes JWT error code issue https://github.com/ably/ably-ruby/issues/204
=> Faraday 1.0 support test

.travis.yml
I know we're planning to Github workflows #208 but before that, following the discussion on Slack I've updated ruby to the current versions, removed redundant and EOL ones. I'll speed up our test suit a bit
=> Update Travis CI versions

.travis.yml, ably.gemspec
Since all changes to statesman are related to ActiveRecord, we can easily update the version of statesman without any changes. This Mr is based https://github.com/ably/ably-ruby/pull/214 since statesman doesn't support EOL versions of Ruby.
Closes: https://github.com/ably/ably-ruby/issues/199
=> Upgrade statesman

ably.gemspec, lib/ably/auth.rb, lib/ably/rest/client.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/rest/auth_spec.rb, spec/acceptance/rest/client_spec.rb, spec/shared/client_initializer_behaviour.rb
Resolves: https://github.com/ably/ably-ruby/issues/182
=> ClientId no longer forces token authentication

README.md
Fixes problems with fury badges not loading.
=> Replace fury badges with shields.io

lib/ably/realtime/connection/websocket_transport.rb
This updates the WebSocket transport to set the SNI hostname when using TLS to ensure clients can connect to endpoints that require SNI, and to always verify the peer certificate to ensure clients are connecting to trusted endpoints.
I've tested the verification manually by attempting to connect to `wrong.host.badssl.com` (which returns a certificate with a different hostname), and the Ably client now reports an error and refuses to connect:
```ruby
require 'eventmachine'
require 'ably'
EventMachine.run do
client = Ably::Realtime.new(
rest_host:     'wrong.host.badssl.com',
realtime_host: 'wrong.host.badssl.com',
key:           ENV['ABLY_KEY'],
log_level:     :debug,
)
client.connection.connect do
p "connected!"
end
end
```
```
12:01:49.094 DEBUG [ -- ] Ably::Realtime::Connection: …
```
=> Set SNI hostname and verify peer certificates when using TLS

README.md
Various small updates, primarily to update links to new ably.com links + canonical support URL ably.com/support
=> Update README with new Ably links

.github/workflows/check.yml, ably.gemspec
statesman is on 8.x now which fixes a Rails 6.1 related deprecation.
In [v8.0.0 on Jan 6](https://github.com/gocardless/statesman/blob/master/CHANGELOG.md#v800-6th-january-2021) they fixed a deprecation, specifically [Use AR Arel table to type cast booleans in order to avoid deprecation warning #421](https://github.com/gocardless/statesman/pull/421)
Without this you get a bunch of deprecation messages, and obviously it'll stop working in Rails 6.2 as the deprecation points out.
This change allows the use of the 8.x line of stateman with ably so that we can upgrade to versions with the fix.
=> Upgrade statesman to ~> 8.0

lib/ably/exceptions.rb, lib/ably/models/connection_details.rb, lib/ably/models/message.rb, lib/ably/models/presence_message.rb, lib/ably/models/protocol_message.rb, lib/ably/realtime/channel/publisher.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, lib/ably/realtime/connection.rb, lib/ably/rest/channel.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/rest/channel_spec.rb, spec/shared/model_behaviour.rb, spec/unit/models/message_spec.rb, spec/unit/models/presence_message_spec.rb, spec/unit/models/protocol_message_spec.rb, spec/unit/realtime/channel_spec.rb, spec/unit/realtime/incoming_message_dispatcher_spec.rb, spec/unit/rest/channel_spec.rb
#247 
- Updated `Message` and `PresenceMessage` classes: added size
- Added `max_message_size` to `ConnectionDetails`
- Updated `ProtocolMessage` (message and presence actions): added `has_correct_message_size?` and `message_size`
- Updated `IncomingMessageDispatcher`.
- Added `MaxMessageSizeExceeded` exception
- Added `MAX_MESSAGE_SIZE` global variable
- Updated `Ably::Rest::Channel#publish`
- Updated `Ably::Realtime::Publisher#enqueue_messages_on_connection`
- Added rspec units, models, acceptance tests
=> Update client options support to 1.1 spec level (maxMessageSize)

lib/ably.rb, lib/ably/agent.rb, lib/ably/realtime/connection.rb, lib/ably/rest/client.rb, lib/ably/version.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/rest/client_spec.rb, spec/unit/rest/client_spec.rb
#230 
https://github.com/ably/docs/pull/1034
- Removed `X-Ably-Lib` header param
- Added `Ably-Agent` header param to the REST client headers
- overwrite agent for example `Ably::Rest::Client.new(agent: 'ably-ruby/1.1.5 ruby/1.9.3')`
- Added `agent` parameter to the realtime client connection auth_deferrable params
- Removed `Ably.lib_variant`
- Added `Ably::AGENT` in `lib/ably/agent.rb`
- Fixed specs
- Updated `ably-ruby-rest` https://github.com/ably/ably-ruby-rest/pull/17
=> Implement RSC7d (Ably-Agent header)

lib/ably/exceptions.rb, lib/ably/models/connection_details.rb, lib/ably/rest/client.rb, spec/acceptance/rest/client_spec.rb, spec/shared/model_behaviour.rb
Resolves #245 
Checking body size in the `Ably::Rest::Client#request` (for `:post`, `:patch`, `:put` methods only).
=> TO3l9 Max frame size

lib/ably/realtime/channel/channel_manager.rb, spec/acceptance/realtime/channel_history_spec.rb
Based on https://github.com/ably/ably-ruby/pull/227 because it uses channel properties. So please, check only 8da823e0f404737f3667ca114917246bfae7a630
Resolves: https://github.com/ably/ably-ruby/issues/113
Added separate test specifically for
> also check that UPDATE updates serial
=> Update attach_serial before emiting UPDATE event

.github/workflows/check.yml, ably.gemspec, spec/spec_helper.rb
Added `coverallsapp/github-action@1.1.3` to `check.yml`
Removed coveralls gem. Updated `ably.gemspec`
Added `simplecov-lcov`.
Set up parallel job and flag for uploading coverage data.
Docs: https://github.com/marketplace/actions/coveralls-github-action
=> New Coveralls Github Actions implementation

spec/acceptance/realtime/connection_failures_spec.rb
`pending` inside the `it() { ... }` block will still execute callbacks, for example `before` callback.
Marked one spec with `xit()` and commented `pending()`
=> Using xit() instead of pending() inside it() {} block

.github/workflows/check.yml, README.md, ably.gemspec, spec/acceptance/realtime/auth_spec.rb
Resolves #220
Added ruby 3.0 to the github workflow action matrix
Updated README.md (Ruby 3.0 support and eventmachine `openssl-dir` issue)
Added webrick development requirement (required by Rest client development)
Similar pull request for Ably Rest gem https://github.com/ably/ably-ruby-rest/pull/18
=> Ruby 3.0 support

lib/ably/realtime/connection.rb, spec/acceptance/realtime/connection_spec.rb
TLS hostname validation CVE-2020-13482
https://github.com/igrigorik/em-http-request/issues/339 for details.
Added `tls: { verify_peer: true }` parameter to `EventMachine::HttpRequest.new()`
=> Enabled TLS hostname validation CVE-2020-13482

spec/acceptance/realtime/connection_spec.rb
As a part of https://github.com/ably/ably-ruby/issues/244
=> Add a spec for #RTN11c

SPEC.md, lib/ably/models/protocol_message.rb, lib/ably/realtime/connection/connection_manager.rb, spec/unit/models/protocol_message_spec.rb
As part of https://github.com/ably/ably-ruby/issues/244
=> Remove deprecated ProtocolMessage#connection_key TR4e

lib/ably/realtime/channel/channel_state_machine.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/realtime/connection/connection_state_machine.rb, spec/acceptance/realtime/connection_spec.rb
Connecting from failed state clears error reasons and reinitializes channels
As part of https://github.com/ably/ably-ruby/issues/244
=> Change behavior when reconnecting from failed state (RTN11d)

spec/acceptance/realtime/connection_spec.rb
Connection#close for suspended/disconnected methods immediately closes the connection
As part of https://github.com/ably/ably-ruby/issues/244
=> Add spec for RTN12d

lib/ably/models/error_info.rb, spec/unit/models/error_info_spec.rb
TI1, RSC7c
Resolves #275
Added missing request_id and cause attributes to the ErrorInfo class.
=> Added request_id and cause attributes to the ErrorInfo class TI1, RSC7c

lib/ably/realtime/channel.rb, lib/ably/rest/channel.rb
Resolves #271 
`Channel#set_options` (RSL7) was implemented as `Channel#update_options`.
Added aliases: `Channel#options=` and `Channel#set_options`
=> Added Channel#set_options and Channel#options= aliases

lib/ably/models/delta_extras.rb, lib/ably/models/message.rb, spec/unit/models/delta_extras_spec.rb, spec/unit/models/message_spec.rb
Resolves #273
Added `DeltaExtras` class and `Message#delta_extras`
=> Added DeltaExtras class and Message#delta_extras method. (TM2i)

spec/acceptance/realtime/connection_spec.rb
As part of https://github.com/ably/ably-ruby/issues/244
=> Add specs for RTN12f

spec/acceptance/realtime/channel_spec.rb
https://ably.atlassian.net/browse/SDK-1097
=> Add specs for RTL17

lib/ably/models/connection_details.rb, lib/ably/realtime/channel/publisher.rb, lib/ably/realtime/connection.rb, lib/ably/rest/channel.rb, lib/ably/rest/client.rb, spec/acceptance/realtime/channel_spec.rb, spec/acceptance/rest/channel_spec.rb, spec/unit/realtime/channel_spec.rb, spec/unit/rest/channel_spec.rb, spec/unit/rest/client_spec.rb
Allowing `max_message_size` for Realtime client. Client gets `max_message_size` from current `connection.details`. `ConnectionDetails` attributes are populated when connection is in `CONNECTED` state.
Added `max_message_size` to `Ably::Rest::Client`.
=> Allowing ConnectionDetails#max_message_size

lib/ably/modules/conversions.rb, lib/ably/realtime/channel.rb, lib/ably/rest/channel.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/rest/message_spec.rb
Resolves #283
```ruby
channel.publish 'click', { x: 1, y: 2 }
message = { name: 'click', data: { x: 1, y: 2 } }
channel.publish message
messages = [
{ name: 'click', data: { x: 1, y: 2 } },
{ name: 'click', data: { x: 2, y: 3 } }
]
channel.publish messages
messages = [
Ably::Models::Message(name: 'click', data: { x: 1, y: 2 })
Ably::Models::Message(name: 'click', data: { x: 2, y: 3 })
]
channel.publish messages
message = Ably::Models::Message(name: 'click', data: { x: 1, y: 2 })
channel.publish message
```
=> RSL1a, RSL1b

lib/ably/auth.rb, lib/ably/models/token_details.rb, spec/acceptance/rest/auth_spec.rb, spec/unit/models/token_details_spec.rb
=> Add support for RSA4b, b1, c, RSA16 (Authentication)

UPDATING.md, lib/ably/rest/client.rb, spec/acceptance/rest/channel_spec.rb, spec/acceptance/rest/message_spec.rb
Related to https://ably-docs.herokuapp.com/client-lib-development-guide/features/#TO3n
Resolves #351
=> Fix REST client idempotent_rest_publishing issue.

spec/unit/logger_spec.rb
* Adds `prevent_log_stubbing` to avoid `allow_any_instance_of` mock on Logger interfering with mocks from specs
* Rewrites spec to be shorter and more readable
I've rerun the test suite a few times and error don't appear anymore
=> Rewrite logger unit spec to reduce flakiness

lib/ably/models/channel_details.rb, lib/ably/models/channel_metrics.rb, lib/ably/models/channel_occupancy.rb, lib/ably/models/channel_status.rb, lib/ably/rest/channel.rb, spec/acceptance/rest/channel_spec.rb, spec/unit/models/channel_details_spec.rb, spec/unit/models/channel_metrics_spec.rb, spec/unit/models/channel_occupancy_spec.rb, spec/unit/models/channel_status_spec.rb
=> Add RSL8, RSL8a lifecycle channel status

lib/ably/realtime/channel.rb
Fixed incorrect channel state class from https://github.com/ably/ably-ruby/blob/main/lib/ably/realtime/channel.rb#L29
=> Fix doc comment: incorrect channel.state type

lib/ably/models/protocol_message.rb, lib/ably/realtime/client/incoming_message_dispatcher.rb, spec/unit/models/protocol_message_spec.rb, spec/unit/realtime/incoming_message_dispatcher_spec.rb
Resolves #377
`TO3l8` specifies the requirement of the SDK to validate message size for outbound messages so the check for inbound messages is not needed. Moreover the existing implementation reads `connection_details` from the `MESSAGE` protocol message (which is always unset) and falls back to the library default, so doesn't work when an account has a configured max_message_size
=> fix: remove inbound message size validation

.github/workflows/check.yml
I noticed that this repository was still using the archived and obsoleted instance of this action from the `ably-labs` org.
=> Use the correct release of the test observability action

.github/workflows/check.yml
We want the workflow run to fail if any of the jobs fails.
The motivation for the current configuration is not clear to me, but I’m guessing the idea was that the failure of a single job shouldn’t cancel the others. Turning off fail-fast should do the same thing.
(Copied from ably-js commit ddef9f7.)
=> Turn off `continue-on-error` in CI

ably.gemspec, lib/ably/realtime/connection.rb, spec/acceptance/realtime/connection_spec.rb
Resolves #396.
(The tests pass when combined with @sacOO7’s WIP test fixes from #391; see #403.)
=> [ECO-4767] Fix server certificate validation for HTTP in Realtime

.github/workflows/check.yml, .github/workflows/docs.yml, Gemfile, ably.gemspec, lib/ably/realtime/channel.rb, lib/ably/realtime/connection.rb, lib/ably/util/crypto.rb, spec/acceptance/realtime/channel_history_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/unit/models/token_details_spec.rb, spec/unit/util/crypto_spec.rb
- Add support for latest ruby versions 3.2 and 3.3
- Fixed failing test due to old simplecov dependency
- For more info => https://github.com/simplecov-ruby/simplecov/issues/1003
- Fixed #394
=> [ECO-4688] Fix tests

lib/ably/realtime/channel/channel_manager.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/connection/connection_manager.rb, lib/ably/realtime/presence.rb, lib/ably/realtime/presence/members_map.rb, lib/ably/realtime/presence/presence_manager.rb, spec/acceptance/realtime/presence_spec.rb, spec/unit/realtime/connection_spec.rb
- Fixed #392 
- Improvement of previous closed PR https://github.com/ably/ably-ruby/pull/405
**PR description** 
- renamed `:in_sync` enum to `:sync_completed`, since `:in_sync` is a very confusing term and doesn't go as per spec.
- removed `resume_sync_proc` code that does client initiated sync when channel attaches with `has_presence` flag. This doesn't go as per spec. 
- added `on_attach` method to `presence_manager` that 
1. start or end sync depending on `has_presence` flag
2. enter local members when `on_attach` method is called.
- Added a new `enter_client_with_id` method to presence that enters local members with `id`. Earlier local members were entered at the end of the sync and didn't support entering members with given id.
=> [ECO-4686][Protocol-2] Implement internal presence

spec/acceptance/rest/channel_spec.rb
Replace error message checks with error code checks. Error messages are not guaranteed to be consistent across versions/systems but the error codes are.
=> rest/channel_spec: fix test checking error messages

lib/ably/auth.rb, lib/ably/realtime/auth.rb, lib/ably/realtime/connection.rb, lib/ably/realtime/presence/members_map.rb, lib/ably/rest/client.rb
Fixed #414 
1. Added client_id_for_request method
2. Added method client_id_for_request_sync to realtime auth
3. Annotated implementation with right spec
=> [ECO-4845] Fix wildcard clientId 

spec/acceptance/realtime/channel_spec.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_failures_spec.rb, spec/acceptance/realtime/connection_spec.rb, spec/acceptance/realtime/message_spec.rb, spec/acceptance/realtime/presence_spec.rb, spec/shared/client_initializer_behaviour.rb, spec/unit/realtime/channels_spec.rb
- Related to #378 
- Most of the changes are related to `Making sure connection state is connected before attaching channel` because if reduces flakiness of the tests
- Two skipped tests will be fixed as a part of https://github.com/ably/ably-ruby/issues/425 since they are not part of protocol 2 work.
=> [ECO-4058][Protocol-2] Feature/integration protocol 2 tests

lib/ably/auth.rb, spec/acceptance/realtime/client_spec.rb, spec/acceptance/realtime/connection_spec.rb
- Fixed #425 
- Link to internal conversation - https://ably-real-time.slack.com/archives/C8SPU4589/p1720195925890139?thread_ts=1720167508.719079&cid=C8SPU4589
=> Fix RSA7a clientId

lib/ably/realtime/channel/channel_manager.rb, spec/acceptance/realtime/channel_spec.rb
- Fix lamda block supplied as a part of channel detach, since use of yield inside lamda is not allowed.
- Instead block should be passed and called explicitly.
- https://stackoverflow.com/questions/30649742/declaring-a-ruby-lambda-with-a-yield
=> Fix lamda used in channel detach

CHANGELOG.md, README.md, SPEC.md, lib/ably/version.rb, spec/support/markdown_spec_formatter.rb
- Added support for protocol 2 / no-connection serial.
- Refactored code and removed old implementation for client initiated presence sync.
- Added `createRecoveryKey` method to generate recoveryKey for new connection.
=> Release 1.2.6

spec/acceptance/realtime/auth_spec.rb
They are subject to change, so checking the error code is enough to know that the expected error occurred.
=> spec: Don't assert error messages

lib/ably/models/protocol_message.rb, spec/unit/models/protocol_message_spec.rb
This check is currently failing when calling `as_json` on an incoming `MESSAGE` protocol message — for example, in the case where you receive a message whilst using debug-level logging.
I’m not sure what was the intention of this check, which dates back to 523a4b1 (there, the error message is "(…) cannot generate valid JSON for ProtocolMessage"). It’s not clear to me why a `msgSerial` would be required in order to serialise a protocol message; I can only guess it was intended as some sort of a business logic sense check on outgoing messages.
Perhaps, back then, it was the case that incoming `MESSAGE` protocol messages contained a `msgSerial`, hence causing this check to succeed, but this is certainly no longer the case (even on protocol v1), nor can I see any good reason why it should be. …
=> [ECO-4970] Remove check for `msg_serial` when converting protocol message to JSON
